// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxnnpoyydwvplgvjawnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4bm5wb3l5ZHd2cGxndmphd25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzQ5NDgsImV4cCI6MjA1OTkxMDk0OH0.V8v_P7QYfAVJxI6Ji3429yQJ8fr0xJPPwdGw8WxTZ2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);